### ISSUE TITLE
local image not found

### ISSUE THREAD

**Issue by zabojad** [blinkreaction/boot2docker-vagrant#15]
The command `vagrant up` fails on pulling local images (even when those images have been built with boot2docker).

``` bash
==> boot2docker: Pulling image symfony/code:latest...
==> boot2docker: Pulling repository symfony/code
==> boot2docker: Traceback (most recent call last):
==> boot2docker:   File "/usr/local/bin/docker-compose", line 9, in <module>
==> boot2docker:     load_entry_point('docker-compose==1.2.0', 'console_scripts', 'docker-compose')()
==> boot2docker:   File "/usr/local/lib/python2.7/dist-packages/docker_compose-1.2.0-py2.7.egg/compose/cli/main.py", line 31, in main
==> boot2docker:     command.sys_dispatch()
==> boot2docker:   File "/usr/local/lib/python2.7/dist-packages/docker_compose-1.2.0-py2.7.egg/compose/cli/docopt_command.py", line 21, in sys_dispatch
==> boot2docker:     self.dispatch(sys.argv[1:], None)
==> boot2docker:   File "/usr/local/lib/python2.7/dist-packages/docker_compose-1.2.0-py2.7.egg/compose/cli/command.py", line 27, in dispatch
==> boot2docker:     super(Command, self).dispatch(*args, **kwargs)
==> boot2docker:   File "/usr/local/lib/python2.7/dist-packages/docker_compose-1.2.0-py2.7.egg/compose/cli/docopt_command.py", line 24, in dispatch
==> boot2docker:     self.perform_command(*self.parse(argv, global_options))
==> boot2docker:   File "/usr/local/lib/python2.7/dist-packages/docker_compose-1.2.0-py2.7.egg/compose/cli/command.py", line 59, in perform_command
==> boot2docker:     handler(project, command_options)
==> boot2docker:   File "/usr/local/lib/python2.7/dist-packages/docker_compose-1.2.0-py2.7.egg/compose/cli/main.py", line 464, in up
==> boot2docker:     do_build=not options['--no-build'],
==> boot2docker:   File "/usr/local/lib/python2.7/dist-packages/docker_compose-1.2.0-py2.7.egg/compose/project.py", line 208, in up
==> boot2docker:     do_build=do_build):
==> boot2docker:   File "/usr/local/lib/python2.7/dist-packages/docker_compose-1.2.0-py2.7.egg/compose/service.py", line 214, in recreate_containers
==> boot2docker:     **override_options)
==> boot2docker:   File "/usr/local/lib/python2.7/dist-packages/docker_compose-1.2.0-py2.7.egg/compose/service.py", line 199, in create_container
==> boot2docker:     stream_output(output, sys.stdout)
==> boot2docker:   File "/usr/local/lib/python2.7/dist-packages/docker_compose-1.2.0-py2.7.egg/compose/progress_stream.py", line 37, in stream_output
==> boot2docker:     print_output_event(event, stream, is_terminal)
==> boot2docker:   File "/usr/local/lib/python2.7/dist-packages/docker_compose-1.2.0-py2.7.egg/compose/progress_stream.py", line 50, in print_output_event
==> boot2docker:     raise StreamOutputError(event['errorDetail']['message'])
==> boot2docker: compose.progress_stream.StreamOutputError: Error: image symfony/code:latest not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

What's wrong ?

**Comment by lmakarov** [comment]
@zabojad what does `docker images` say?

**Comment by zabojad** [comment]
@lmakarov it says this:

``` bash
bash-3.2$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
symfony/php-fpm     latest              07c346d0d46d        2 days ago          496.7 MB
<none>              <none>              598981075e26        2 days ago          423.4 MB
<none>              <none>              aca5792ccd36        2 days ago          423.4 MB
<none>              <none>              6d7d2272a823        2 days ago          350.5 MB
symfony/nginx       latest              b71a49532b96        3 days ago          227.6 MB
<none>              <none>              7b6b9f75e0ae        3 days ago          338.7 MB
symfony/code        latest              3cba1a08d808        3 days ago          188.3 MB
ubuntu              14.04               07f8e8c5e660        4 weeks ago         188.3 MB
ubuntu              latest              07f8e8c5e660        4 weeks ago         188.3 MB
willdurand/elk      latest              91e748253ae4        4 weeks ago         1.098 GB
mysql               latest              56f320bd6adc        5 weeks ago         282.9 MB
hello-world         latest              91c95931e552        6 weeks ago         910 B
```

And those images work fine with boot2docker / docker-compose up (without vagrant).

**Comment by lmakarov** [comment]
@zabojad sounds like you may have both boot2docker and boot2docker-vagrant used at the same time.

Try `boot2docker stop`, then `export DOCKER_HOST=tcp://localhost:2375` (this will point your docker client to the boot2docker-vagrant VM) and then `docker images`.

**Comment by zabojad** [comment]
``` bash
pc1:docker thomasfetiveau$ boot2docker stop
pc1:docker thomasfetiveau$ export DOCKER_HOST=tcp://localhost:2375
pc1:docker thomasfetiveau$ docker images
FATA[0000] Cannot connect to the Docker daemon. Is 'docker -d' running on this host? 
pc1:docker thomasfetiveau$ docker -d
2015/05/30 17:45:51 This is a client-only binary - running the Docker daemon is not supported.
```

What should I do then ?

**Comment by lmakarov** [comment]
@zabojad that means that you either do not have boot2docker-vagrant running at all or there was a port conflict (e.g. stock boot2docker was running when you launched boot2docker-vagrant) and vagrant automatically fixed this by assigning different ports, this way `tcp://localhost:2375` would no longer be a valid endpoint.
1. Shutdown all VirtualBox VMs
2. `vagrant up` in the folder where you installed this project
3. `export DOCKER_HOST=tcp://localhost:2375`
4. `docker version` and `docker images`

**Comment by joshbenner** [comment]
Also note, if you had boot2docker, it may have set other env vars which may need to be removed. We had seen one issue caused by a lingering docker TLS env var from boot2docker init.

**Comment by lmakarov** [comment]
@zabojad do you still have this issue?

**Comment by lmakarov** [comment]
Closing for the lack of feedback. Feel free to reopen if the issue reoccurs.
